In [230]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
pd.options.mode.chained_assignment = None

root = 'C:/Data/for-you/'
import os

In [231]:
apps = pd.read_csv('applicants_cleans.csv')

In [232]:
apps.head()

userid  age_bin  classification  \
0  95030aef3e970680d882f1527f549d9e        4               5   
1  68ad76832a913de0d62df103b3d5b807        1               3   
2  959d8992667c8bfc1ac665f234360eb6        3               5   
3  76b067cd5f3e1b1976d2e2eeceedf567        1               3   
4  f44cfb96520a82e172ce2ae116b21187        3               4   

   first_generation  datascience_experience  num_hackathons_attended  \
0                 0                       2                        0   
1                 1                       2                        0   
2                 1                       2                        0   
3                 0                       1                        0   
4                 0                       1                        0   

                                workshop_suggestions  undergrad  Masters  PhD  \
0  Python Fundamentals (Functions/Loops)\nVisuali...          0        1    0   
1  Training videos on different levels of machine...          1        0    0   
2                                                NaN          0        1    0   
3                                Python data science          1        0    0   
4                                                NaN          1        0    0   

   ...  Anthropology  Public Service and Administration  school_0  school_1  \
0  ...             0                                  0         0         0   
1  ...             0                                  0         0         0   
2  ...             0                                  0         0         0   
3  ...             0                                  0         0         0   
4  ...             0                                  0         0         0   

   school_2  school_3  school_4  school_5  school_6  school_7  
0         0         0         0         0         0         1  
1         0         0         0         0         0         1  
2         0         0         0         0         1         0  
3         0         0         0         0         1         1  
4         0         0         0         0         0         1  

[5 rows x 118 columns]

In [233]:
cols_to_drop = [i for i in apps.columns if 'school' in i]

In [234]:
apps.drop(cols_to_drop, axis = 1, inplace = True)

In [235]:
import pickle

pkl_file = open('industries.pkl', 'rb')
industries = pickle.load(pkl_file) 
pkl_file.close()

pkl_file = open('technologies.pkl', 'rb')
technologies = pickle.load(pkl_file) 
pkl_file.close()

pkl_file = open('majors.pkl', 'rb')
majors = pickle.load(pkl_file) 
pkl_file.close()

In [236]:
majors = [i for i in majors if len(i)>0]
industries = [i for i in industries if len(i)>0]
technologies = [i for i in technologies if len(i)>0]

In [237]:
apps.drop(majors, axis = 1, inplace = True)
apps.drop(industries, axis = 1, inplace = True)

In [238]:
apps.drop(['workshop_suggestions', 'Has_minor'], axis = 1, inplace = True)

In [239]:
apps.head()

userid  age_bin  classification  \
0  95030aef3e970680d882f1527f549d9e        4               5   
1  68ad76832a913de0d62df103b3d5b807        1               3   
2  959d8992667c8bfc1ac665f234360eb6        3               5   
3  76b067cd5f3e1b1976d2e2eeceedf567        1               3   
4  f44cfb96520a82e172ce2ae116b21187        3               4   

   first_generation  datascience_experience  num_hackathons_attended  \
0                 0                       2                        0   
1                 1                       2                        0   
2                 1                       2                        0   
3                 0                       1                        0   
4                 0                       1                        0   

   undergrad  Masters  PhD  Excel  ...  MATLAB  Pytorch  Scikit-learn  \
0          0        1    0      1  ...       0        0             0   
1          1        0    0      1  ...       1        0             0   
2          0        1    0      0  ...       0        1             1   
3          1        0    0      1  ...       1        0             0   
4          1        0    0      0  ...       0        0             0   

   full_stack  TensorFlow  R  SQL  dev_ops  Keras  cloud  
0           0           0  0    0        0      0      0  
1           0           0  0    0        0      0      0  
2           1           0  0    0        0      0      0  
3           0           0  0    0        0      0      0  
4           0           0  0    0        0      0      0  

[5 rows x 24 columns]

In [240]:
bootcamp = pd.read_csv(root+'bootcamp_turnout.csv')
workshops = pd.read_csv(root+'workshops.csv')

In [241]:
bootcamp.head()

userid  \
0  f48d02fd46d249ab2c37f925f405139f   
1  f48d02fd46d249ab2c37f925f405139f   
2  f4610ad445934181ac9982f6ba818907   
3  f4610ad445934181ac9982f6ba818907   
4  f4610ad445934181ac9982f6ba818907   

                                            workshop  
0                           Data Science: Start Here  
1                      Getting a Job in Data Science  
2                            Story Telling With Data  
3  Convolutional Neural Networks & Semantic Segme...  
4                       Machine Learning: Start Here

In [242]:
workshops[workshops.event == 'Bootcamp 2020']

event                                   workshop  \
13  Bootcamp 2020  Hacking Unsupervised Custering Algorithms   
14  Bootcamp 2020                     CNN's and Segmentation   
15  Bootcamp 2020                     Storytelling with Data   
16  Bootcamp 2020               Machine Learning: Start Here   
17  Bootcamp 2020              Getting a Job in Data Science   
18  Bootcamp 2020                     Model Interpretability   
19  Bootcamp 2020                   Data Science: Start Here   
20  Bootcamp 2020                Natural Language Processing   

                                                 tags  \
13  clustering, unsupervised, k-means, gaussian mi...   
14  computer vision, image recognition, image proc...   
15  presenting, impact, business, data science, ho...   
16  regression, theory, math, accuracy interpretab...   
17  resume, linkedin, professional, job, interview...   
18  feature importance plots, partial dependence p...   
19  pandas, import, packages, data science, wrangl...   
20  sklearn, gensim, nltk, tfidf, TfidfVectorizer,...   

                                          description     track  difficulty  
13  In this workshop, I am going to take you to th...        ML           2  
14  I will start by talking about the convolution ...        DL           3  
15  In this talk, we will describe how we use data...  Industry           0  
16  Did you know that all machine learning is real...        ML           2  
17  In my talk I'll be covering how to apply for a...  Industry           0  
18  In this session on model interpretability, we ...        ML           2  
19  First, we'll dive into a process known as "dat...        DS           1  
20  Interested in learning what Natural Language P...        ML           2

In [243]:
workshops[workshops.event != 'Bootcamp 2020']

event                              workshop  \
0   TD 2020                Introduction to Python   
1   TD 2020                Storytelling with Data   
2   TD 2020             Stats for Data Scientists   
3   TD 2020              How To Win TAMU Datathon   
4   TD 2020  Intro to Natural Language Processing   
5   TD 2020                        Data Wrangling   
6   TD 2020                    Data Visualization   
7   TD 2020     Machine Learning Interpretability   
8   TD 2020              Intro to Neural Networks   
9   TD 2020     Machine Learning Part 1/2: Theory   
10  TD 2020                Reinforcement Learning   
11  TD 2020    Machine Learning Part 2/2: Applied   
12  TD 2020                Recommendation Engines   

                                                 tags  \
0   for, loops, functions, while, logic, variables...   
1          presenting, impact, business, data science   
2   statistics, confidence interval, testing, stat...   
3                    win, advice, datathon, hackathon   
4   sklearn, gensim, nltk, tfidf, TfidfVectorizer,...   
5   jupyter notebook, pandas, import, packages, da...   
6   viz, visualization, seaborn, matplotlib, plots...   
7   explainability, partial dependence, LIME, cond...   
8   neural networks, machine learning, introductio...   
9   optimization, math, theory, machine learning, ...   
10  RL, stock, trading, games, robotics, deep lear...   
11  applied, random forests, decision trees, xgboo...   
12  information retrieval, recommendation engine, ...   

                                          description     track  difficulty  
0   Are you new to programming? Or do you want a r...        CS           0  
1   In this talk, we will describe how we use data...  Industry           0  
2   In this talk, we will discuss some aspects of ...        DS           0  
3   Learn how to win at TAMU Datathon from last ye...  Industry           0  
4   Interested in learning what Natural Language P...        ML           2  
5   Today, we'll dive into a process known as "dat...        DS           1  
6   Today, we'll cover data visualization and the ...        DS           1  
7   In this session on model interpretability, we ...        ML           2  
8   hidden layers, edges, nodes, backwards propaga...        DL           2  
9   Before you dive into some of the hot ML algori...        ML           1  
10  Beyond supervised and unsupervised learning, d...        DL           3  
11  In this workshop we will take you though one o...        ML           1  
12  Reccommendation engines drive much of our onli...        ML           2

In [244]:
workshops = workshops.replace({'workshop' :{'Storytelling with Data':'Story Telling With Data',
                                "CNN's and Segmentation":'Convolutional Neural Networks & Semantic Segmentation',
                                'Hacking Unsupervised Custering Algorithms':'Hacking Unsupervised Clustering Algorithms'}})

In [245]:
bootcamp = bootcamp.merge(workshops, on ='workshop', how = 'left')
bootcamp = bootcamp.drop(['workshop', 'event', 'tags', 'description'], axis = 1)
bootcamp.head()

userid     track  difficulty
0  f48d02fd46d249ab2c37f925f405139f        DS           1
1  f48d02fd46d249ab2c37f925f405139f  Industry           0
2  f4610ad445934181ac9982f6ba818907  Industry           0
3  f4610ad445934181ac9982f6ba818907  Industry           0
4  f4610ad445934181ac9982f6ba818907        DL           3

In [246]:
joined = bootcamp.merge(apps, on = 'userid', how = 'left')
joined.head()

userid     track  difficulty  age_bin  \
0  f48d02fd46d249ab2c37f925f405139f        DS           1        2   
1  f48d02fd46d249ab2c37f925f405139f  Industry           0        2   
2  f4610ad445934181ac9982f6ba818907  Industry           0        0   
3  f4610ad445934181ac9982f6ba818907  Industry           0        0   
4  f4610ad445934181ac9982f6ba818907        DL           3        0   

   classification  first_generation  datascience_experience  \
0               4                 0                       1   
1               4                 0                       1   
2               2                 0                       3   
3               2                 0                       3   
4               2                 0                       3   

   num_hackathons_attended  undergrad  Masters  ...  MATLAB  Pytorch  \
0                        0          1        0  ...       0        0   
1                        0          1        0  ...       0        0   
2                        2          1        0  ...       0        0   
3                        2          1        0  ...       0        0   
4                        2          1        0  ...       0        0   

   Scikit-learn  full_stack  TensorFlow  R  SQL  dev_ops  Keras  cloud  
0             0           0           0  0    0        0      0      0  
1             0           0           0  0    0        0      0      0  
2             1           0           1  0    0        0      1      1  
3             1           0           1  0    0        0      1      1  
4             1           0           1  0    0        0      1      1  

[5 rows x 26 columns]

In [247]:
joined.shape

(228, 26)

In [248]:
target1 = 'difficulty'
traget2 = 'track'
feature_names = joined.columns.drop(['userid', 'track', 'difficulty'])
y1 = joined[target1]
y2 = joined[traget2]
X = joined[feature_names]

In [259]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

In [250]:
from sklearn.model_selection import cross_val_score, GridSearchCV

### Classification for difficulty considering ordinality

In [251]:
y1.value_counts()

2    84
0    75
1    49
3    20
Name: difficulty, dtype: int64

In [252]:
y1_greater_than_0 = [1 if i>0 else 0 for i in y1]
y1_greater_than_1 = [1 if i>1 else 0 for i in y1]
y1_greater_than_2 = [1 if i>2 else 0 for i in y1]

In [253]:
clf1_0 = RandomForestClassifier(class_weight='balanced')
clf1_1 = RandomForestClassifier(class_weight='balanced')
clf1_2 = RandomForestClassifier(class_weight='balanced')

In [254]:
cross_val_score(clf1_0, X, y1_greater_than_0, scoring = 'f1')

array([0.75      , 0.58181818, 0.66666667, 0.66666667, 0.66666667])

In [255]:
cross_val_score(clf1_1, X, y1_greater_than_1, scoring = 'f1')

array([0.35294118, 0.30769231, 0.22222222, 0.46153846, 0.13333333])

In [256]:
cross_val_score(clf1_2, X, y1_greater_than_2, scoring = 'f1')

array([0., 0., 0., 0., 0.])

In [257]:
clf1_0.fit(X, y1_greater_than_0)
clf1_1.fit(X, y1_greater_than_1)
clf1_2.fit(X, y1_greater_than_2)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [258]:
predicted_class = clf1_0.predict(X) + clf1_1.predict(X) + clf1_2.predict(X)

confusion_matrix(y1, predicted_class)

array([[33, 23, 12,  7],
       [14, 25,  9,  1],
       [ 8, 18, 35, 23],
       [ 1,  4,  5, 10]], dtype=int64)

In [260]:
print(classification_report(y1, predicted_class))

              precision    recall  f1-score   support

           0       0.59      0.44      0.50        75
           1       0.36      0.51      0.42        49
           2       0.57      0.42      0.48        84
           3       0.24      0.50      0.33        20

    accuracy                           0.45       228
   macro avg       0.44      0.47      0.43       228
weighted avg       0.50      0.45      0.46       228



### Multiclass classification for track

In [261]:
y2.value_counts()

ML          84
Industry    75
DS          49
DL          20
Name: track, dtype: int64

In [262]:
clf2 = RandomForestClassifier()
clf2

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [263]:
clf2.fit(X, y2)
clf2.score(X, y2)

0.5614035087719298

In [264]:
print(cross_val_score(clf2, X, y2, scoring = 'f1_macro'))

[0.11309524 0.14583333 0.29962779 0.30175439 0.21802961]


In [265]:
param_grid  = { 'n_estimators': np.arange(20, 200, step=20),
                'criterion': ['entropy', 'gini'],    
                'class_weight': ['balanced'],
                'max_features' : ['auto'],
                'max_depth' : np.arange(4, 10, step=2),
                'min_samples_split' : np.arange(8, 15, step=3),
                'min_samples_leaf' : np.arange(2, 5, step=1)}

In [266]:
rf_model = RandomForestClassifier()
grid1 = GridSearchCV(estimator=rf_model, param_grid=param_grid, n_jobs=-1, cv=3, verbose=1, scoring = 'f1_macro')
grid1.fit(X, y2)

Fitting 3 folds for each of 486 candidates, totalling 1458 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    2.7s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    5.6s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:   10.4s
[Parallel(n_jobs=-1)]: Done 784 tasks      | elapsed:   17.8s
[Parallel(n_jobs=-1)]: Done 1234 tasks      | elapsed:   27.7s
[Parallel(n_jobs=-1)]: Done 1458 out of 1458 | elapsed:   33.2s finished


GridSearchCV(cv=3, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,...
             iid='deprecated', n_jobs=-1,
             param_grid={'class_weight': ['balanced'],
              

In [267]:
clf2 = grid1.best_estimator_
clf2.fit(X, y2)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=6, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=11,
                       min_weight_fraction_leaf=0.0, n_estimators=180,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [268]:
confusion_matrix(y2, clf2.predict(X))

array([[ 7,  1,  4,  8],
       [ 3, 33,  7,  6],
       [10, 22, 30, 13],
       [15, 18, 17, 34]], dtype=int64)

### Workshop Recommendation

In [269]:
feature_names

Index(['age_bin', 'classification', 'first_generation',
       'datascience_experience', 'num_hackathons_attended', 'undergrad',
       'Masters', 'PhD', 'Excel', 'Python', 'Tableau', 'Pandas', 'NumPy',
       'MATLAB', 'Pytorch', 'Scikit-learn', 'full_stack', 'TensorFlow', 'R',
       'SQL', 'dev_ops', 'Keras', 'cloud'],
      dtype='object')

In [317]:
workshops = workshops.drop_duplicates('workshop', keep='first')
workshops.track[workshops.track == 'CS'] = 'DS'
workshops = workshops.drop(['event', 'tags', 'description'], axis = 1)
workshops

workshop     track  difficulty  \
0                              Introduction to Python        DS           0   
1                             Story Telling With Data  Industry           0   
2                           Stats for Data Scientists        DS           0   
3                            How To Win TAMU Datathon  Industry           0   
4                Intro to Natural Language Processing        ML           2   
5                                      Data Wrangling        DS           1   
6                                  Data Visualization        DS           1   
7                   Machine Learning Interpretability        ML           2   
8                            Intro to Neural Networks        DL           2   
9                   Machine Learning Part 1/2: Theory        ML           1   
10                             Reinforcement Learning        DL           3   
11                 Machine Learning Part 2/2: Applied        ML           1   
12                             Recommendation Engines        ML           2   
13         Hacking Unsupervised Clustering Algorithms        ML           2   
14  Convolutional Neural Networks & Semantic Segme...        DL           3   
16                       Machine Learning: Start Here        ML           2   
17                      Getting a Job in Data Science  Industry           0   
18                             Model Interpretability        ML           2   
19                           Data Science: Start Here        DS           1   
20                        Natural Language Processing        ML           2   

    rank1  rank2  
0       4    NaN  
1       4    1.0  
2       4    3.0  
3       4    1.0  
4       2    2.0  
5       1    3.0  
6       1    3.0  
7       2    2.0  
8       2    4.0  
9       1    2.0  
10      3    4.0  
11      1    2.0  
12      2    2.0  
13      2    2.0  
14      3    4.0  
16      2    2.0  
17      4    1.0  
18      2    2.0  
19      1    3.0  
20      2    2.0

In [328]:
import pickle 

output = open('workshops.pkl', 'wb')
pickle.dump(workshops, output)
output.close()

pkl_file = open('workshops.pkl', 'rb')
workshops = pickle.load(pkl_file) 
pkl_file.close()

In [329]:
pickle.dump(clf1_0, open('clf1_0.pkl','wb'))
pickle.dump(clf1_1, open('clf1_1.pkl','wb'))
pickle.dump(clf1_2, open('clf1_2.pkl','wb'))
pickle.dump(clf2, open('clf2.pkl','wb'))

In [325]:
def get_workshops_recommendation(diff_0, diff_1, diff_2, DL, DS, Industry, ML, rec_df):
        
    rec_df['rank1'] = 0 
    if diff_0 == 0:
        rec_df['rank1'] = rec_df.difficulty.rank(method = 'dense')
    elif diff_1 == 0:
        rec_df['rank1'] = [1 if i==1 else 4 for i in rec_df.difficulty]
        rec_df.rank1[rec_df.difficulty == 2] = 2
        rec_df.rank1[rec_df.difficulty == 3] = 3
    elif diff_2 == 0:
        rec_df['rank1'] = [1 if i==2 else 4 for i in rec_df.difficulty]
        rec_df.rank1[rec_df.difficulty == 3] = 2
        rec_df.rank1[rec_df.difficulty == 1] = 3
    else:
        rec_df['rank1'] = rec_df.difficulty.rank(method = 'dense', ascending = False)
    
    rec_df['rank2'] = rec_df.track
    rec_df['rank2'] = rec_df['rank2'].map({'DL':DL, 'DS':DS, 'Industry':Industry, 'ML':ML})
    rec_df['rank2'] = rec_df.rank2.rank(method = 'dense', ascending = False)
    
    rec_df = rec_df.sort_values(['rank1', 'rank2']).reset_index(drop = True)
    rec_df['overall_rank'] = rec_df.index + 1
    return rec_df

In [326]:
def workshop_recommendations(age_bin, classification, first_generation, datascience_experience, 
                            num_hackathons_attended, technology):
    
    age = {'(15, 18]' : 0, '(18, 20]': 1, '(20, 22]': 2, '(22, 25]': 3, '(25, 30]' : 4, '(30, 50]': 5}
    
    class_dict = {'O': 0, 'Fr':1 , 'So':2, 'Jr':3, 'Sr':4, 'Ma':5, 'PhD':6}
    undergrad = [1 if classification in ('Jr', 'Sr', 'So', 'Fr') else 0][0]
    Masters = [1 if classification == 'Ma' else 0][0]
    PhD = [1 if classification == 'PhD' else 0][0]
    
    f_g = [1 if first_generation=='True' else 0][0]
    
    datahack_dict = {'0':0, '1-3':1, '4-7':2, '8-10':3, '10+':4}

    techs = []
    for i in technologies:
        techs = techs + [1 if i in technology else 0]
        
    feats = [age[age_bin], class_dict[classification], f_g, int(datascience_experience), 
             datahack_dict[num_hackathons_attended], undergrad, Masters, PhD] + techs
     
    feats = np.array(feats).reshape(1, -1)        
    
    diff_0, diff_1, diff_2 = clf1_0.predict(feats), clf1_1.predict(feats), clf1_2.predict(feats)
    
    DL, DS, Industry, ML = clf2.predict_proba(feats)[0,0], clf2.predict_proba(feats)[0,1], \
        clf2.predict_proba(feats)[0,2], clf2.predict_proba(feats)[0,3]
    
    workshops_df = get_workshops_recommendation(diff_0, diff_1, diff_2, DL, DS, Industry, ML, workshops)
    
    return workshops_df

In [327]:
workshop_recommendations(age_bin='(22, 25]', classification = 'Ma', first_generation = 'True', datascience_experience = 2,
                        num_hackathons_attended = '1-3', technology = ['Python', 'Pandas', 'Numpy', 'R', 'SQL'])

workshop     track  difficulty  \
0                   Machine Learning Part 1/2: Theory        ML           1   
1                  Machine Learning Part 2/2: Applied        ML           1   
2                                      Data Wrangling        DS           1   
3                                  Data Visualization        DS           1   
4                            Data Science: Start Here        DS           1   
5                Intro to Natural Language Processing        ML           2   
6                   Machine Learning Interpretability        ML           2   
7                              Recommendation Engines        ML           2   
8          Hacking Unsupervised Clustering Algorithms        ML           2   
9                        Machine Learning: Start Here        ML           2   
10                             Model Interpretability        ML           2   
11                        Natural Language Processing        ML           2   
12                           Intro to Neural Networks        DL           2   
13                             Reinforcement Learning        DL           3   
14  Convolutional Neural Networks & Semantic Segme...        DL           3   
15                            Story Telling With Data  Industry           0   
16                           How To Win TAMU Datathon  Industry           0   
17                      Getting a Job in Data Science  Industry           0   
18                             Introduction to Python        DS           0   
19                          Stats for Data Scientists        DS           0   

    rank1  rank2  overall_rank  
0       1    2.0             1  
1       1    2.0             2  
2       1    3.0             3  
3       1    3.0             4  
4       1    3.0             5  
5       2    2.0             6  
6       2    2.0             7  
7       2    2.0             8  
8       2    2.0             9  
9       2    2.0            10  
10      2    2.0            11  
11      2    2.0            12  
12      2    4.0            13  
13      3    4.0            14  
14      3    4.0            15  
15      4    1.0            16  
16      4    1.0            17  
17      4    1.0            18  
18      4    3.0            19  
19      4    3.0            20